---

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Disable password logins via ssh
  lineinfile: dest={{ sshd_config_path }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  notify: restart_ssh

- name: Create regular user
  user: name={{ remote_user }} groups=sudo shell=/bin/bash

- name: Enable password-less sudo
  lineinfile: dest=/etc/sudoers state=present regexp='^%sudo ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL'

- name: Disable ssh for root user
  # TODO

- name: Firewall
  # TODO

- name: Add public key from local machine to remote ~admin/.ssh/authorized_keys
  authorized_key: user={{ remote_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
