---

###############################################################################
- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }}
       update_cache=yes
       state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
    - unattended-upgrades
    - ufw
    - fail2ban
  tags: packages


###############################################################################
- name: Automatically install security updates
  copy: src=templates/autoinstall_security_updates.txt
        dest=/etc/apt/apt.conf.d/10periodic


###############################################################################
- name: Disable password logins via ssh
  lineinfile: dest={{ sshd_config_path }}
              regexp="^#?PasswordAuthentication"
              line="PasswordAuthentication no"
  notify: restart_ssh


###############################################################################
- name: Create regular user
  user: name={{ remote_user }}
        groups=sudo
        shell=/bin/bash


###############################################################################
- name: Enable password-less sudo
  lineinfile: dest=/etc/sudoers
              state=present
              regexp='^%sudo ALL\='
              line='%sudo ALL=(ALL) NOPASSWD:ALL'


###############################################################################
- name: Add public key from local machine to remote ~/.ssh/authorized_keys
  authorized_key: user={{ remote_user }}
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


###############################################################################
- name: Disable ssh for root user
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart_ssh


###############################################################################
- name: firewall - close all ports
  ufw: state=enabled
       policy=deny


###############################################################################
- name: firewall - open ssh port
  ufw: rule=allow
       port=22
       proto=tcp


###############################################################################
- name: firewall - open http port
  ufw: rule=allow
       port=80
       proto=tcp
