---

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Disable password logins via ssh
  lineinfile: dest={{ sshd_config_path }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  notify: restart_ssh

- name: Create regular user
  user: name={{ remote_user }} groups=sudo

- name: Auto-install security packages
  # TODO

- name: Disable ssh for root user
  # TODO

- name: Firewall
  # TODO

