---

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Disable password logins via ssh
  # TODO

- name: Add user as sudo
  # TODO

- name: Auto-install security packages
  # TODO

- name: Disable ssh for root user
  # TODO

- name: Firewall
  # TODO

